export enum Categories {
  Antiques = 'Antiques & collectables',
  BabyGear = 'Baby gear',
  Books = 'Books',
  BuildingRenovation = 'Building & renovation',
  BusinessFarmingIndustry = 'Business, farming & industry',
  ClothingFashion = 'Clothing & fashion',
  Computers = 'Computers',
  ElectronicsPhotography = 'Electronics & photography',
  Gaming = 'Gaming',
  HealthBeauty = 'Health & beauty',
  HomeLiving = 'Home & living',
  JewelleryWatches = 'Jewellery & watches',
  MobilePhones = 'Mobile phones',
  MusicInstruments = 'Music & instruments',
  PetsAnimals = 'Pets & animals',
  Sports = 'Sports',
  ToysModels = 'Toys & models',
  LastChance = 'Last chance',
  Services = 'Services',
  Stores = 'Stores',
  AllCategories = 'View all categories '
}
